backend.url=http://192.168.31.112:8080/api/v1/
job.max-radius-km=50
assignment.mode=FIRST_ACCEPT
monetisation.enabled=false
monetisation.model=PER_JOB
monetisation.allow_browse_without_payment=true
app.debug_enabled=true
auth.otp.resend_delay_seconds=300