server.port=8085
spring.application.name=workly-auth-service

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017,localhost:27018,localhost:27019/workly?replicaSet=rs0
spring.data.mongodb.auto-index-creation=true

# Redis Sentinel
spring.data.redis.sentinel.master=mymaster
spring.data.redis.sentinel.nodes=localhost:26379,localhost:26380,localhost:26381

# JWT
auth.token.ttl-hours=24
auth.token.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# SMS
sms.provider=mock

# Logging
logging.level.com.workly=DEBUG
