server.port=8084
spring.application.name=workly-config-service

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/workly_config

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
