spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: workly-server
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27018,localhost:27019/workly?replicaSet=rs0
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    postgresql:
      uri: jdbc:postgresql://localhost:6432/workly
      username: workly
      password: password

  elasticsearch:
    uris: http://localhost:9200
    socket-timeout: 10s
    username: elastic
    password: password

  datasource:
    url: jdbc:postgresql://localhost:6432/workly
    username: workly
    password: password
    driver-class-name: org.postgresql.Driver

  config:
    sync:
      notification-interval-hours: 1

  kafka:
    listener:
      concurrency: 3
    bootstrap-servers: 127.0.0.1:9094,127.0.0.1:9095,127.0.0.1:9096
    consumer:
      group-id: workly-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    com.workly: DEBUG
    org.springframework.security: DEBUG
    org.apache.kafka.clients.NetworkClient: WARN


server:
  port: 8080
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
    instances:
      searchService:
        baseConfig: default
      fcm:
        baseConfig: default
      fcmBatch:
        baseConfig: default

workly:
  features:
    payments:
      enabled: false
    sms:
      enabled: false

app:
  mode: monolith # monolith | microservice
  region: india

job:
  max-radius-km: 100
  assignment:
    mode: FIRST_ACCEPT # FIRST_ACCEPT | MANUAL_SELECT

sms:
  provider: mock # mock | fast2sms

monetisation:
  enabled: false
  model: PER_JOB # SUBSCRIPTION | PER_JOB
  allow_browse_without_payment: true

auth:
  token:
    ttl-hours: 24
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

custom:
  location:
    update-interval-minutes: 60
  auth:
    otp:
      resend-delay-seconds: 300
  app:
    debug-enabled: true
  job:
    max-radius-km: 50
    min-advance-hours: 2
  assignment:
    mode: FIRST_ACCEPT
  monetisation:
    enabled: false
    model: PER_JOB
    allow-browse-without-payment: true
  chat:
    url: ws://192.168.31.112:8082/ws/chat

search-service:
  url: http://localhost:8080
