server.port=8082
spring.application.name=workly-chat-service

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017,localhost:27018,localhost:27019/workly_chat?replicaSet=rs0
spring.data.mongodb.auto-index-creation=true

# Redis
spring.data.redis.sentinel.master=mymaster
spring.data.redis.sentinel.nodes=localhost:26379,localhost:26380,localhost:26381

# Kafka
spring.kafka.bootstrap-servers=127.0.0.1:9094,127.0.0.1:9095,127.0.0.1:9096
spring.kafka.consumer.group-id=chat-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# JWT Secret (Should be same as Server)
app.jwtSecret=worklySecretKeyForJwtAuthenticationPleaseChangeIdeally
app.jwtExpirationMs=86400000

# Logging
logging.level.com.workly.chat=DEBUG
