server.port=8083
spring.application.name=workly-search-service

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/workly_search

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.socket-timeout=10s
spring.elasticsearch.username=elastic
spring.elasticsearch.password=password
