server.port=8083
spring.application.name=workly-search-service

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017,localhost:27018,localhost:27019/workly_search?replicaSet=rs0
# Redis
spring.data.redis.sentinel.master=mymaster
spring.data.redis.sentinel.nodes=localhost:26379,localhost:26380,localhost:26381

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.socket-timeout=10s
spring.elasticsearch.username=elastic
spring.elasticsearch.password=password
